In [116]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", 200)

In [3]:
data_path = "dataset/H_MHAS_c2.dta" 
df = pd.read_stata(data_path)

In [4]:
df.shape

(26839, 5241)

In [5]:
df.head(5)

,codent01,codent03,ps3,ent2,np,unhhidnp,rahhidnp,tipent_01,tipent_03,tipent_12,tipent_15,tipent_18,unhhid,cunicah,h1hhid,h2hhid,h3hhid,h4hhid,h5hhid,h1hhidc,h2hhidc,h3hhidc,h4hhidc,h5hhidc,acthog,subhog_01,subhog_03,subhog_12,subhog_15,subhog_18,s1hhidnp,s2hhidnp,s3hhidnp,s4hhidnp,s5hhidnp,inw1,inw2,inw3,inw4,inw5,r1iwstat,r2iwstat,r3iwstat,r4iwstat,r5iwstat,s1iwstat,s2iwstat,s3iwstat,s4iwstat,s5iwstat,hacohort,r1proxy,r2proxy,r3proxy,r4proxy,r5proxy,s1proxy,s2proxy,s3proxy,s4proxy,s5proxy,h1hhresp,h2hhresp,h3hhresp,h4hhresp,h5hhresp,h1cpl,h2cpl,h3cpl,h4cpl,h5cpl,r1wthh,r2wthh,r3wthh,r4wthh,r5wthh,r1wtresp,r2wtresp,r3wtresp,r4wtresp,r5wtresp,s1wtresp,s2wtresp,s3wtresp,s4wtresp,s5wtresp,r1iwm,r2iwm,r3iwm,r4iwm,r5iwm,s1iwm,s2iwm,s3iwm,s4iwm,s5iwm,r1iwy,r2iwy,r3iwy,r4iwy,...,s2fsad,s3fsad,s4fsad,s5fsad,r1ftired,r2ftired,r3ftired,r4ftired,r5ftired,s1ftired,s2ftired,s3ftired,s4ftired,s5ftired,r1energ,r2energ,r3energ,r4energ,r5energ,s1energ,s2energ,s3energ,s4energ,s5energ,r1cesd_m,r2cesd_m,r3cesd_m,r4cesd_m,r5cesd_m,s1cesd_m,s2cesd_m,s3cesd_m,s4cesd_m,s5cesd_m,r1cesdm_m,r2cesdm_m,r3cesdm_m,r4cesdm_m,r5cesdm_m,s1cesdm_m,s2cesdm_m,s3cesdm_m,s4cesdm_m,s5cesdm_m,r3lideal3,r4lideal3,r5lideal3,s3lideal3,s4lideal3,s5lideal3,r3lexcl3,r4lexcl3,r5lexcl3,s3lexcl3,s4lexcl3,s5lexcl3,r3lstsf3,r4lstsf3,r5lstsf3,s3lstsf3,s4lstsf3,s5lstsf3,r3limptt3,r4limptt3,r5limptt3,s3limptt3,s4limptt3,s5limptt3,r3lchnot3,r4lchnot3,r5lchnot3,s3lchnot3,s4lchnot3,s5lchnot3,r3lsatsc3,r4lsatsc3,r5lsatsc3,s3lsatsc3,s4lsatsc3,s5lsatsc3,r3lsatsc3m,r4lsatsc3m,r5lsatsc3m,s3lsatsc3m,s4lsatsc3m,s5lsatsc3m,r3satlife_m,r4satlife_m,r5satlife_m,s3satlife_m,s4satlife_m,s5satlife_m,r3satlifez,r4satlifez,r5satlifez,s3satlifez,s4satlifez,s5satlifez,r2cantril,s2cantril
0,1.Selected person,1.Selected person in 2001,1.0,1.0,10,110.0,110,"12.Direct, second interview","12.Direct, second interview","1.Direct, follow-up interview",NaN,NaN,1,1,10.0,11.0,11.0,41.0,109.0,10,11,11,41,109,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010",31.NP=010 Deceased,99.Not part of the study,120.0,120.0,120.0,NaN,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","0.Non, resp","0.Non, resp","1.Resp, alive","1.Resp, alive","1.Resp, alive","5.NR, died this wave","6.NR, died prev wave","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,NaN,Baseline sample,0.Not proxy,0.Not proxy,0.Not proxy,NaN,NaN,0.Not proxy,0.Not proxy,0.Not proxy,NaN,NaN,2.0,2.0,2.0,NaN,NaN,1.Yes,1.Yes,1.Yes,NaN,NaN,312.0,314.0,313.0,444.0,NaN,300.0,314.0,329.0,296.0,NaN,300.0,314.0,329.0,NaN,NaN,7.0,8.0,11.0,NaN,NaN,7.0,8.0,11.0,NaN,NaN,2001.0,2003.0,2012.0,NaN,...,0.No,0.No,NaN,NaN,1.Yes,1.Yes,1.Yes,NaN,NaN,0.No,0.No,0.No,NaN,NaN,1.Yes,0.No,0.No,NaN,NaN,1.Yes,0.No,1.Yes,NaN,NaN,7.0,3.0,9.0,NaN,NaN,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,3.Agree,NaN,NaN,3.Agree,NaN,NaN,3.Agree,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,3.Agree,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,2.6,NaN,NaN,2.2,NaN,NaN,0,5,5,0.0,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,1.510731,NaN,NaN,1.510731,NaN,NaN,1.0,NaN
1,2.Spouse of selected person,2.Spouse of selected person in 2001,2.0,2.0,20,120.0,120,"11.Direct, first interview","11.Direct, first interview","1.Direct, follow-up interview","1.Direct, follow-up interview","1.Direct, follow-up interview",1,1,10.0,11.0,11.0,22.0,22.0,10,11,11,22,22,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010",12.New HH contains NP=020,12.New HH contains NP=020,110.0,110.0,110.0,NaN,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,NaN,Baseline sample,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.Yes,1.Yes,1.Yes,0.No,0.No,312.0,314.0,313.0,444.0,296.0,300.0,314.0,329.0,296.0,288.0,300.0,314.0,329.0,NaN,NaN,7.0,8.0,11.0,11.0,12.0,7.0,8.0,11.0,NaN,NaN,2001.0,2003.0,2012.0,2015.0,...,0.No,1.Yes,NaN,NaN,0.No,0.No,0.No,1.Yes,1.Yes,1.Yes,1.Yes,1.Yes,NaN,NaN,1.Yes,0.No,1.Yes,0.No,1.Yes,1.Yes,0.No,0.No,NaN,NaN,1.0,1.0,0.0,6.0,3.0,7.0,3.0,9.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,3.Agree,3.Agree,3.Agree,3.Agree,NaN,NaN,2.Neutral,2.Neutral,3.Agree,3.Agree,NaN,NaN,2.Neutral,3.Agree,3.Agree,2.Neutral,NaN,NaN,2.Neutral,3.Agree,3.Agree,3.Agree,NaN,NaN,2.Neutral,3.Agree,3.Agree,2.Neutral,NaN,NaN,2.2,2.8,3.0,2.6,NaN,NaN,0,0,0,0.0,NaN,NaN,2.Neutral,1.Agree,1.Agree,2.Neutral,NaN,NaN,1.510731,-0.387025,-0.393398,1.510731,NaN,NaN,NaN,1.0
2,1.Selected person,1.Selected person in 2001,1.0,1.0,10,210.0,210,"11.Direct, first interview","22.Proxy, second interview","1.Direct, follow-up interview","1.Direct, follow-up interview","1.Direct, follow-up interview",2,2,20.0,21.0,21.0,21.0,31.0,20,21,21,21,31,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010","01.No change, HH contains NP=010",11.New HH contains NP=010,220.0,220.0,220.0,220.0,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,Baseline sample,0.Not proxy,1.Proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,1.Proxy,1.Proxy,NaN,2.0,2.0,2.0,2.0,1.0,1.Yes,1.Yes,1.Yes,1.Yes,0.No,263.0,265.0,264.0,375.0,250.0,253.0,265.0,278.0,250.0,273.0,0.0,0.0,0.0,239.0,NaN,6.0,6.0,11.0,10.0,12.0,6.0,6.0,10.0,10.0,NaN,2001.0,2003.0,2012.0,2015.0,...,1.Yes,NaN,NaN,NaN,1.Yes,NaN,1.Yes,1.Yes,1.Yes,1.Yes,0.No,NaN,NaN,NaN,0.No,NaN,0.No,0.No,1.Yes,0.No,0.No,NaN,NaN,NaN,4.0,NaN,8.0,7.0,1.0,2.0,4.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0,0.0,0.0,0.0,9.0,9.0,NaN,3.Agree,2.Neutral,3.Agree,NaN,NaN,NaN,3.Agree,2.Neutral,3.Agree,NaN,NaN,NaN,3.Agree,3.Agree,3.Agree,NaN,NaN,NaN,3.Agree,3.Agree,3.Agree,NaN,NaN,NaN,3.Agree,3.Agree,3.Agree,NaN,NaN,NaN,3.0,2.6,3.0,NaN,NaN,NaN,0,0,0,5.0,5.0,NaN,1.Agree,1.Agree,1.Agree,NaN,NaN,NaN,-0.397267,-0.387025,-0.393398,NaN,NaN,NaN,NaN,5.0
3,2.Spouse of selected person,2.Spouse of selected person in 2001,2.0,2.0,20,220.0,220,"12.Direct, second interview","11.Direct, first interview","3.Proxy, follow-up interview","3.Proxy, follow-up interview",NaN,2,2,20.0,21.0,21.0,21.0,52.0,20,21,21,21,52,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010","01.No change, HH contains NP=010",32.NP=020 Deceased,210.0,210.0,210.0,210.0,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","0.Non, resp","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","5.NR, died this wave","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,Baseline sample,0.Not proxy,0.Not proxy,1.Proxy,1.Proxy,NaN,0.Not proxy,1.Proxy,0.Not proxy,0.Not proxy,NaN,2.0,2.0,2.0,2.0,NaN,1.Yes,1.Yes,1.Yes,1.Yes,NaN,263.0,0.0,264.0,375.0,250.0,0.0,0.0,0.0,239.0,239.0,253.0,265.0,278.0,250.0,NaN,6.0,6.0,10.0,10.0,NaN,6.0,6.0,11.0,10.0,NaN,2001.0,2003.0,2012.0,2015.0,...,NaN,1.Yes,1.Yes,NaN,1.Yes,0.No,NaN,NaN,NaN,1.Yes,NaN,1.Yes,1.Yes,NaN,0.No,0.No,NaN,NaN,NaN,0.No,NaN,0.No,0.No,NaN,2.0,4.0,NaN,NaN,NaN,4.0,NaN,8.0,7.0,NaN,0.0,0.0,9.0,9.0,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,3.Agree,2.Neutral,NaN,NaN,NaN,NaN,3.Agree,2.Neutral,NaN,NaN,NaN,NaN,3.Agree,3.Agree,NaN,NaN,NaN,NaN,3.Agree,3.Agree,NaN,NaN,NaN,NaN,3.Agree,3.Agree,NaN,NaN,NaN,NaN,3.0,2.6,NaN,5,5,5,0.0,0.0,NaN,NaN,NaN,NaN,1.Agree,1.Agree,NaN,NaN,NaN,NaN,-0.397267,-0.387025,NaN,5.0,NaN
4,1.Selected person,1.Selected person in 2001,1.0,1.0,10,310.0,310,"11.Direct, first interview","11.Direct, first interview","1.Direct, follow-up interview","1.Direct, follow-up interview","1.Direct, follow-up interview",3,3,30.0,41.0,31.0,31.0,31.0,30,41,31,31,31,01,00.Baseline HH,11.New HH contains NP=010,"01.No change, HH contains NP=010","01.No change, HH contains NP=010","01.No change, HH contains NP=010",311.0,311.0,311.0,311.0,311.0,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",0.Inap,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",Baseline sample,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,NaN,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,1.0,2.0,2.0,2.0,2.0,0.No,1.Yes,1.Yes,1.Yes,1.Yes,471.0,475.0,472.0,669.0,448.0,454.0,475.0,498.0,448.0,435.0,NaN,471.0,494.0,0.0,448.0,6.0,8.0,11.0,11.0,12.0,NaN,8.0,10.0,11.0,12.0,2001.0,2003.0,2012.0,2015.0,...,0.No,0.No,0.No,1.Yes,0.No,0.No,0.No,0.No,1.Yes,NaN,0.No,1.Yes,0.No,1.Yes,0.No,1.Yes,0.No,0.No,0.No,NaN,0.No,1.Yes,1.Yes,1.Yes,3.0,0.0,2.0,1.0,3.0,NaN,1.0,3.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,2.Neutral,3.Agree,2.Neutral,3.Agree,3.Agree,1.Disagree,2.Neutral,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,2.Neutral,3.Agree,3.Agree,1.Disagree,3.Agree,3.Agree,2.4,3.0,2.8,2.6,3.0,2.6,0,0,0,0.0,0.0,0.0,1.Agree,1.Agree,1.Agree,1.Agree,1.Agree,1.Agree,-0.397267,-0.387025,-0.393398,-0.397267,-0.387025,-0.393398,1.0,NaN

In [6]:
column_names = list(df.columns.str.lower())
# column_names

In [7]:
df['unhhidnp'].describe()

count    2.683900e+04
mean     9.459864e+05
std      5.576727e+05
min      1.100000e+02
25%      4.707150e+05
50%      9.409100e+05
75%      1.385115e+06
max      2.021820e+06
Name: unhhidnp, dtype: float64

In [8]:
df['unhhidnp'].isna().sum()

0

In [9]:
# with open(r'column_names.txt', 'w') as fp:
#     fp.write('\n'.join(column_names))

In [122]:
target_columns = ['r1hosp1y',
 'r2hosp1y',
 'r3hosp1y',
 'r4hosp1y',
 'r5hosp1y']

In [123]:
identity_columns = [
"unhhidnp",
"ragender"]

In [124]:
picked_columns = [

# Age at Interview (Months and Years)    
"r1agey",
"r2agey",
"r3agey",
"r4agey",
"r5agey",

# Self-Report of Health
"r1shlt",
"r2shlt",
"r3shlt",
"r4shlt",
"r5shlt",

# Doctor Diagnosed Health Problems: Ever Have Condition
"r1hibpe",
"r2hibpe",
"r3hibpe",
"r4hibpe",
"r5hibpe",
"r1diabe",
"r2diabe",
"r3diabe",
"r4diabe",
"r5diabe",
"r1cancre",
"r2cancre",
"r3cancre",
"r4cancre",
"r5cancre",
"r1respe",
"r2respe",
"r3respe",
"r4respe",
"r5respe",
"r1hrtatte",
"r2hrtatte",
"r3hrtatte",
"r4hrtatte",
"r5hrtatte",

"r4hearte",
"r5hearte",

"r1stroke",
"r2stroke",
"r3stroke",
"r4stroke",
"r5stroke",
"r1arthre",
"r2arthre",
"r3arthre",
"r4arthre",
"r5arthre",
"s5arthre",

# RwBMI is the respondent's self-reported body mass index
"r1bmi",
"r2bmi",
"r3bmi",
"r4bmi",
"r5bmi",

# Health Behaviors: Physical Activity or Exercise
"r1vigact",
"r2vigact",
"r3vigact",
"r4vigact",
"r5vigact",

# Health Behaviors: Smoking (Cigarettes)
"r1smokev",
"r2smokev",
"r3smokev",
"r4smokev",
"r5smokev",
"r1smoken",
"r2smoken",
"r3smoken",
"r4smoken",
"r5smoken",
"r1smokef",
"r2smokef",
"r3smokef",
"r4smokef",
"r5smokef",
"r1strtsmok",
"r2strtsmok",
"r3strtsmok",
"r4strtsmok",
"r5strtsmok",
"r1quitsmok",
"r2quitsmok",
"r3quitsmok",
"r4quitsmok",
"r5quitsmok",

# Health Behaviors: Preventive Care
"r1cholst",
"r2cholst",
"r3cholst",
"r4cholst",
"r5cholst",
"r3flusht",
"r4flusht",
"r5flusht",
"r1breast",
"r2breast",
"r3breast",
"r4breast",
"r5breast",
"r1mammog",
"r2mammog",
"r3mammog",
"r4mammog",
"r5mammog",
"r1papsm",
"r2papsm",
"r3papsm",
"r4papsm",
"r5papsm",
"r1prost",
"r2prost",
"r3prost",
"r4prost",
"r5prost",
]

In [125]:
screening = identity_columns + target_columns + picked_columns
screening

['unhhidnp',
 'ragender',
 'r1hosp1y',
 'r2hosp1y',
 'r3hosp1y',
 'r4hosp1y',
 'r5hosp1y',
 'r1agey',
 'r2agey',
 'r3agey',
 'r4agey',
 'r5agey',
 'r1shlt',
 'r2shlt',
 'r3shlt',
 'r4shlt',
 'r5shlt',
 'r1hibpe',
 'r2hibpe',
 'r3hibpe',
 'r4hibpe',
 'r5hibpe',
 'r1diabe',
 'r2diabe',
 'r3diabe',
 'r4diabe',
 'r5diabe',
 'r1cancre',
 'r2cancre',
 'r3cancre',
 'r4cancre',
 'r5cancre',
 'r1respe',
 'r2respe',
 'r3respe',
 'r4respe',
 'r5respe',
 'r1hrtatte',
 'r2hrtatte',
 'r3hrtatte',
 'r4hrtatte',
 'r5hrtatte',
 'r4hearte',
 'r5hearte',
 'r1stroke',
 'r2stroke',
 'r3stroke',
 'r4stroke',
 'r5stroke',
 'r1arthre',
 'r2arthre',
 'r3arthre',
 'r4arthre',
 'r5arthre',
 's5arthre',
 'r1bmi',
 'r2bmi',
 'r3bmi',
 'r4bmi',
 'r5bmi',
 'r1vigact',
 'r2vigact',
 'r3vigact',
 'r4vigact',
 'r5vigact',
 'r1smokev',
 'r2smokev',
 'r3smokev',
 'r4smokev',
 'r5smokev',
 'r1smoken',
 'r2smoken',
 'r3smoken',
 'r4smoken',
 'r5smoken',
 'r1smokef',
 'r2smokef',
 'r3smokef',
 'r4smokef',
 'r5smokef',
 'r1strtsmok',
 'r2strtsmok',
 'r3strtsmok',
 'r4strtsmok',
 'r5strtsmok',
 'r1quitsmok',
 'r2quitsmok',
 'r3quitsmok',
 'r4quitsmok',
 'r5quitsmok',
 'r1cholst',
 'r2cholst',
 'r3cholst',
 'r4cholst',
 'r5cholst',
 'r3flusht',
 'r4flusht',
 'r5flusht',
 'r1breast',
 'r2breast',
 'r3breast',
 'r4breast',
 'r5breast',
 'r1mammog',
 'r2mammog',
 'r3mammog',
 'r4mammog',
 'r5mammog',
 'r1papsm',
 'r2papsm',
 'r3papsm',
 'r4papsm',
 'r5papsm',
 'r1prost',
 'r2prost',
 'r3prost',
 'r4prost',
 'r5prost']

In [126]:
df_sub = df[screening]
df_sub.head(5)

,unhhidnp,ragender,r1hosp1y,r2hosp1y,r3hosp1y,r4hosp1y,r5hosp1y,r1agey,r2agey,r3agey,r4agey,r5agey,r1shlt,r2shlt,r3shlt,r4shlt,r5shlt,r1hibpe,r2hibpe,r3hibpe,r4hibpe,r5hibpe,r1diabe,r2diabe,r3diabe,r4diabe,r5diabe,r1cancre,r2cancre,r3cancre,r4cancre,r5cancre,r1respe,r2respe,r3respe,r4respe,r5respe,r1hrtatte,r2hrtatte,r3hrtatte,r4hrtatte,r5hrtatte,r4hearte,r5hearte,r1stroke,r2stroke,r3stroke,r4stroke,r5stroke,r1arthre,r2arthre,r3arthre,r4arthre,r5arthre,s5arthre,r1bmi,r2bmi,r3bmi,r4bmi,r5bmi,r1vigact,r2vigact,r3vigact,r4vigact,r5vigact,r1smokev,r2smokev,r3smokev,r4smokev,r5smokev,r1smoken,r2smoken,r3smoken,r4smoken,r5smoken,r1smokef,r2smokef,r3smokef,r4smokef,r5smokef,r1strtsmok,r2strtsmok,r3strtsmok,r4strtsmok,r5strtsmok,r1quitsmok,r2quitsmok,r3quitsmok,r4quitsmok,r5quitsmok,r1cholst,r2cholst,r3cholst,r4cholst,r5cholst,r3flusht,r4flusht,r5flusht,r1breast,r2breast,r3breast,r4breast,r5breast,r1mammog,r2mammog,r3mammog,r4mammog,r5mammog,r1papsm,r2papsm,r3papsm,r4papsm,r5papsm,r1prost,r2prost,r3prost,r4prost,r5prost
0,110.0,1.Man,1.Yes,0.No,0.No,NaN,NaN,59.0,61.0,71.0,NaN,NaN,5.Poor,2.Very good,5.Poor,NaN,NaN,1.yes,1.yes,1.yes,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,NaN,29.068796,NaN,28.719721,NaN,NaN,1.Yes,1.Yes,0.No,NaN,NaN,1.Yes,1.Yes,1.Yes,NaN,NaN,0.No,0.No,0.No,NaN,NaN,0.0,0.0,0.0,NaN,NaN,14.0,14.0,14.0,NaN,NaN,15.0,15.0,25.0,NaN,NaN,1.Yes,1.Yes,1.Yes,NaN,NaN,0.No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.No,0.No,0.No,NaN,NaN
1,120.0,2.Woman,0.No,0.No,0.No,0.No,0.No,50.0,52.0,62.0,65.0,68.0,4.Fair,4.Fair,3.Good,3.Good,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,NaN,20.239502,NaN,20.000000,NaN,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.No,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.Yes,1.Yes,0.No,0.No,1.Yes,0.No,0.No,0.No,1.Yes,1.Yes,1.Yes,1.Yes,0.No,0.No,0.No,0.No,0.No,0.No,1.Yes,1.Yes,1.Yes,0.No,0.No,NaN,NaN,NaN,NaN,NaN
2,210.0,1.Man,0.No,0.No,0.No,0.No,1.Yes,69.0,72.0,81.0,83.0,86.0,5.Poor,NaN,4.Fair,4.Fair,3.Good,0.no,0.no,0.no,0.no,1.yes,0.no,0.no,0.no,0.no,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,1.yes,1.yes,NaN,NaN,39.262234,NaN,26.709404,NaN,0.No,NaN,1.Yes,1.Yes,0.No,1.Yes,0.No,1.Yes,0.No,0.No,1.Yes,0.No,0.No,0.No,0.No,1.0,0.0,0.0,0.0,0.0,14.0,14.0,14.0,14.0,14.0,NaN,NaN,60.0,60.0,60.0,0.No,NaN,1.Yes,1.Yes,1.Yes,0.No,1.Yes,0.No,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.No,0.No,0.No
3,220.0,2.Woman,0.No,0.No,0.No,1.Yes,NaN,48.0,50.0,70.0,74.0,NaN,3.Good,4.Fair,NaN,NaN,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,NaN,NaN,36.444443,22.038568,NaN,NaN,0.No,0.No,NaN,NaN,NaN,0.No,0.No,0.No,0.No,NaN,0.No,0.No,0.No,0.No,NaN,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.No,1.Yes,NaN,1.Yes,NaN,NaN,0.No,NaN,0.No,0.No,NaN,NaN,NaN,0.No,0.No,NaN,NaN,NaN,0.No,1.Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,310.0,1.Man,0.No,0.No,0.No,0.No,0.No,50.0,53.0,62.0,65.0,68.0,3.Good,3.Good,4.Fair,3.Good,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,1.yes,1.yes,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,26.812220,22.437674,28.400547,29.411762,25.605536,0.No,1.Yes,0.No,1.Yes,0.No,1.Yes,0.No,1.Yes,1.Yes,1.Yes,0.No,0.No,0.No,0.No,0.No,0.0,0.0,0.0,0.0,0.0,18.0,18.0,18.0,18.0,18.0,3.0,3.0,36.0,36.0,36.0,0.No,1.Yes,1.Yes,1.Yes,1.Yes,1.Yes,1.Yes,1.Yes,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.Yes,1.Yes,1.Yes,1.Yes,1.Yes

In [127]:
vars_orig = screening[4:]
vars_orig

['r3hosp1y',
 'r4hosp1y',
 'r5hosp1y',
 'r1agey',
 'r2agey',
 'r3agey',
 'r4agey',
 'r5agey',
 'r1shlt',
 'r2shlt',
 'r3shlt',
 'r4shlt',
 'r5shlt',
 'r1hibpe',
 'r2hibpe',
 'r3hibpe',
 'r4hibpe',
 'r5hibpe',
 'r1diabe',
 'r2diabe',
 'r3diabe',
 'r4diabe',
 'r5diabe',
 'r1cancre',
 'r2cancre',
 'r3cancre',
 'r4cancre',
 'r5cancre',
 'r1respe',
 'r2respe',
 'r3respe',
 'r4respe',
 'r5respe',
 'r1hrtatte',
 'r2hrtatte',
 'r3hrtatte',
 'r4hrtatte',
 'r5hrtatte',
 'r4hearte',
 'r5hearte',
 'r1stroke',
 'r2stroke',
 'r3stroke',
 'r4stroke',
 'r5stroke',
 'r1arthre',
 'r2arthre',
 'r3arthre',
 'r4arthre',
 'r5arthre',
 's5arthre',
 'r1bmi',
 'r2bmi',
 'r3bmi',
 'r4bmi',
 'r5bmi',
 'r1vigact',
 'r2vigact',
 'r3vigact',
 'r4vigact',
 'r5vigact',
 'r1smokev',
 'r2smokev',
 'r3smokev',
 'r4smokev',
 'r5smokev',
 'r1smoken',
 'r2smoken',
 'r3smoken',
 'r4smoken',
 'r5smoken',
 'r1smokef',
 'r2smokef',
 'r3smokef',
 'r4smokef',
 'r5smokef',
 'r1strtsmok',
 'r2strtsmok',
 'r3strtsmok',
 'r4strtsmok',
 'r5strtsmok',
 'r1quitsmok',
 'r2quitsmok',
 'r3quitsmok',
 'r4quitsmok',
 'r5quitsmok',
 'r1cholst',
 'r2cholst',
 'r3cholst',
 'r4cholst',
 'r5cholst',
 'r3flusht',
 'r4flusht',
 'r5flusht',
 'r1breast',
 'r2breast',
 'r3breast',
 'r4breast',
 'r5breast',
 'r1mammog',
 'r2mammog',
 'r3mammog',
 'r4mammog',
 'r5mammog',
 'r1papsm',
 'r2papsm',
 'r3papsm',
 'r4papsm',
 'r5papsm',
 'r1prost',
 'r2prost',
 'r3prost',
 'r4prost',
 'r5prost']

In [128]:
from collections import OrderedDict
vars_clean = list(OrderedDict.fromkeys([name[2:] for name in vars_orig]))
vars_clean

['hosp1y',
 'agey',
 'shlt',
 'hibpe',
 'diabe',
 'cancre',
 'respe',
 'hrtatte',
 'hearte',
 'stroke',
 'arthre',
 'bmi',
 'vigact',
 'smokev',
 'smoken',
 'smokef',
 'strtsmok',
 'quitsmok',
 'cholst',
 'flusht',
 'breast',
 'mammog',
 'papsm',
 'prost']

In [129]:
from pprint import pprint

# Initialize an empty DataFrame with the desired final columns
# accumulated_df = pd.DataFrame(columns=final_columns)
accumulated_df = None

# Loop over the wave numbers
for wave in range(1, 6):
    # Create new column names for the current wave
    _names = [f"r{wave}{var}" for var in vars_clean]
    wave_column_names = [name for name in _names if name in df_sub.columns] # Only keep valid column names
    # print(wave_column_names)
    column_mapping = {name: name[2:] for name in wave_column_names}  
    # print(column_mapping)

    # Select the necessary columns from the subset DataFrame and rename them
    wave_df = df_sub[identity_columns + wave_column_names].copy()
    wave_df = wave_df.rename(columns=column_mapping)

    # Insert the wave number as a new column
    wave_df.insert(0, "wave", wave)

    # Append the current wave's DataFrame to the accumulated DataFrame
    if accumulated_df is None:
        accumulated_df = wave_df.copy()
    else:
        accumulated_df = pd.concat([accumulated_df, wave_df])

In [130]:
accumulated_df.shape

(134195, 27)

In [131]:
accumulated_df.head()

,wave,unhhidnp,ragender,hosp1y,agey,shlt,hibpe,diabe,cancre,respe,hrtatte,stroke,arthre,bmi,vigact,smokev,smoken,smokef,strtsmok,quitsmok,cholst,breast,mammog,papsm,prost,flusht,hearte
0,1,110.0,1.Man,1.Yes,59.0,5.Poor,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,29.068796,1.Yes,1.Yes,0.No,0.0,14.0,15.0,1.Yes,NaN,NaN,NaN,0.No,NaN,NaN
1,1,120.0,2.Woman,0.No,50.0,4.Fair,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,0.No,0.No,0.0,NaN,NaN,1.Yes,1.Yes,0.No,1.Yes,NaN,NaN,NaN
2,1,210.0,1.Man,0.No,69.0,5.Poor,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,1.Yes,1.Yes,1.0,14.0,NaN,0.No,NaN,NaN,NaN,NaN,NaN,NaN
3,1,220.0,2.Woman,0.No,48.0,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,0.No,0.No,0.0,NaN,NaN,0.No,0.No,0.No,0.No,NaN,NaN,NaN
4,1,310.0,1.Man,0.No,50.0,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,26.812220,0.No,1.Yes,0.No,0.0,18.0,3.0,0.No,NaN,NaN,NaN,1.Yes,NaN,NaN

In [132]:
accumulated_df.iloc[:,2:].head()

,ragender,hosp1y,agey,shlt,hibpe,diabe,cancre,respe,hrtatte,stroke,arthre,bmi,vigact,smokev,smoken,smokef,strtsmok,quitsmok,cholst,breast,mammog,papsm,prost,flusht,hearte
0,1.Man,1.Yes,59.0,5.Poor,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,29.068796,1.Yes,1.Yes,0.No,0.0,14.0,15.0,1.Yes,NaN,NaN,NaN,0.No,NaN,NaN
1,2.Woman,0.No,50.0,4.Fair,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,0.No,0.No,0.0,NaN,NaN,1.Yes,1.Yes,0.No,1.Yes,NaN,NaN,NaN
2,1.Man,0.No,69.0,5.Poor,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,1.Yes,1.Yes,1.0,14.0,NaN,0.No,NaN,NaN,NaN,NaN,NaN,NaN
3,2.Woman,0.No,48.0,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,0.No,0.No,0.0,NaN,NaN,0.No,0.No,0.No,0.No,NaN,NaN,NaN
4,1.Man,0.No,50.0,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,26.812220,0.No,1.Yes,0.No,0.0,18.0,3.0,0.No,NaN,NaN,NaN,1.Yes,NaN,NaN

In [133]:
# Prepare new clean dataset
df_clean = accumulated_df.iloc[:,2:].dropna(subset=["hosp1y"]).copy()
cols = list(df_clean)  # Get a list of column names
cols[0], cols[1] = cols[1], cols[0]  # Swap the first two names
df_clean = df_clean.reindex(columns=cols)  # Reindex the DataFrame with the new column order

In [134]:
df_clean.head(5).T

                  0        1       2        3         4
hosp1y        1.Yes     0.No    0.No     0.No      0.No
ragender      1.Man  2.Woman   1.Man  2.Woman     1.Man
agey           59.0     50.0    69.0     48.0      50.0
shlt         5.Poor   4.Fair  5.Poor   3.Good    3.Good
hibpe         1.yes     0.no    0.no     0.no      0.no
diabe          0.no     0.no    0.no     0.no      0.no
cancre         0.no     0.no    0.no     0.no      0.no
respe          0.no     0.no    0.no     0.no      0.no
hrtatte        0.no     0.no    0.no     0.no      0.no
stroke         0.no     0.no    0.no     0.no      0.no
arthre         0.no     0.no    0.no     0.no      0.no
bmi       29.068796      NaN     NaN      NaN  26.81222
vigact        1.Yes     0.No    0.No     0.No      0.No
smokev        1.Yes     0.No   1.Yes     0.No     1.Yes
smoken         0.No     0.No   1.Yes     0.No      0.No
smokef          0.0      0.0     1.0      0.0       0.0
strtsmok       14.0      NaN    14.0      NaN      18.0
quitsmok       15.0      NaN     NaN      NaN       3.0
cholst        1.Yes    1.Yes    0.No     0.No      0.No
breast          NaN    1.Yes     NaN     0.No       NaN
mammog          NaN     0.No     NaN     0.No       NaN
papsm           NaN    1.Yes     NaN     0.No       NaN
prost          0.No      NaN     NaN      NaN     1.Yes
flusht          NaN      NaN     NaN      NaN       NaN
hearte          NaN      NaN     NaN      NaN       NaN

In [135]:
df_clean.shape

(76353, 25)

In [136]:
df_clean.isna().sum()

hosp1y          0
ragender        0
agey           34
shlt         5727
hibpe         578
diabe         584
cancre        536
respe         518
hrtatte       516
stroke        493
arthre        529
bmi         13793
vigact       5847
smokev         44
smoken         54
smokef         72
strtsmok    42317
quitsmok    53011
cholst       3703
breast      35155
mammog      35167
papsm       35531
prost       47743
flusht      30310
hearte      44562
dtype: int64

In [137]:
df_clean.dtypes

hosp1y      category
ragender    category
agey         float64
shlt        category
hibpe       category
diabe       category
cancre      category
respe       category
hrtatte     category
stroke      category
arthre      category
bmi          float32
vigact      category
smokev      category
smoken      category
smokef       float64
strtsmok     float64
quitsmok     float64
cholst      category
breast      category
mammog      category
papsm       category
prost       category
flusht      category
hearte      category
dtype: object

In [138]:
df_clean.hosp1y.value_counts()

hosp1y
0.No     67160
1.Yes     9193
Name: count, dtype: int64

In [139]:
for col in df_clean.columns:
    print(col)
    print(list(df_clean[col].unique()))

hosp1y
['1.Yes', '0.No']
ragender
['1.Man', '2.Woman']
agey
[59.0, 50.0, 69.0, 48.0, 64.0, 53.0, 56.0, 52.0, 73.0, 58.0, 55.0, 54.0, 26.0, 80.0, 87.0, 84.0, 72.0, 71.0, 75.0, 41.0, 57.0, 67.0, 82.0, 61.0, 76.0, 47.0, 49.0, 51.0, 42.0, 37.0, 45.0, 68.0, 65.0, 62.0, 34.0, 60.0, 77.0, 92.0, 38.0, 39.0, 74.0, 70.0, 46.0, 40.0, 63.0, 83.0, 66.0, 32.0, 79.0, 78.0, 35.0, 90.0, 81.0, 44.0, 43.0, 88.0, 96.0, 89.0, 91.0, 85.0, 86.0, 27.0, 36.0, 93.0, 95.0, 31.0, 101.0, 99.0, 30.0, 18.0, 29.0, 94.0, 33.0, 104.0, 28.0, 98.0, 22.0, 24.0, 25.0, 19.0, 105.0, 97.0, 100.0, 20.0, 103.0, 21.0, 106.0, nan, 107.0, 23.0, 110.0, 115.0, 102.0, 112.0, 113.0, 16.0]
shlt
['5.Poor', '4.Fair', '3.Good', nan, '2.Very good', '1.Excellent']
hibpe
['1.yes', '0.no', nan]
diabe
['0.no', '1.yes', nan]
cancre
['0.no', nan, '1.yes']
respe
['0.no', '1.yes', nan]
hrtatte
['0.no', nan, '1.yes']
stroke
['0.no', '1.yes', nan]
arthre
['0.no', '1.yes', nan]
bmi

In [140]:
# Prepare target value
df_clean.hosp1y = (df_clean.hosp1y == "1.Yes").astype(int)

In [141]:
from sklearn.model_selection import train_test_split

In [142]:
df_full_train, df_test = train_test_split(
    df_clean,
    test_size=0.2,
    random_state=1,
)

df_train, df_val = train_test_split(
    df_full_train,
    test_size= (0.2 / 0.8),
    random_state=1,
)

len(df_train), len(df_val), len(df_test)

(45811, 15271, 15271)

In [143]:
# Reset index and get y vectors
target = "hosp1y"

df_train = df_train.reset_index(drop=True)
df_val = df_val.reset_index(drop=True)
df_test = df_test.reset_index(drop=True)

y_train = df_train[target].values
y_val = df_val[target].values
y_test = df_test[target].values
        
del df_train[target] 
del df_val[target] 
del df_test[target]

# EDA

In [144]:
df_full_train.head()

,hosp1y,ragender,agey,shlt,hibpe,diabe,cancre,respe,hrtatte,stroke,arthre,bmi,vigact,smokev,smoken,smokef,strtsmok,quitsmok,cholst,breast,mammog,papsm,prost,flusht,hearte
12736,0,2.Woman,85.0,NaN,1.yes,0.no,0.no,0.no,0.no,0.no,1.yes,22.222221,NaN,1.Yes,0.No,0.0,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13631,0,2.Woman,65.0,1.Excellent,0.no,0.no,1.yes,0.no,0.no,0.no,0.no,23.781212,1.Yes,1.Yes,1.Yes,0.0,14.0,1.0,1.Yes,1.Yes,1.Yes,1.Yes,NaN,1.Yes,NaN
9500,0,1.Man,69.0,3.Good,1.yes,0.no,0.no,0.no,1.yes,0.no,0.no,30.477968,0.No,1.Yes,0.No,0.0,17.0,49.0,1.Yes,NaN,NaN,NaN,1.Yes,0.No,0.no
1019,0,1.Man,88.0,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,1.Yes,0.No,0.0,40.0,30.0,1.Yes,NaN,NaN,NaN,0.No,NaN,NaN
8804,0,2.Woman,86.0,4.Fair,0.no,0.no,0.no,0.no,0.no,1.yes,0.no,NaN,0.No,0.No,0.No,0.0,36.0,NaN,0.No,0.No,0.No,0.No,NaN,1.Yes,0.no

In [145]:
df_full_train = df_full_train.reset_index(drop=True)

In [146]:
df_full_train.hosp1y.value_counts(normalize=True)

hosp1y
0    0.880325
1    0.119675
Name: proportion, dtype: float64

In [147]:
global_hospitalization_rate = df_full_train.hosp1y.mean()
print(f"{global_hospitalization_rate:.2f}")

0.12

In [148]:
df_full_train.dtypes

hosp1y         int64
ragender    category
agey         float64
shlt        category
hibpe       category
diabe       category
cancre      category
respe       category
hrtatte     category
stroke      category
arthre      category
bmi          float32
vigact      category
smokev      category
smoken      category
smokef       float64
strtsmok     float64
quitsmok     float64
cholst      category
breast      category
mammog      category
papsm       category
prost       category
flusht      category
hearte      category
dtype: object

In [149]:
df_full_train.dtypes.ne("category")

hosp1y       True
ragender    False
agey         True
shlt        False
hibpe       False
diabe       False
cancre      False
respe       False
hrtatte     False
stroke      False
arthre      False
bmi          True
vigact      False
smokev      False
smoken      False
smokef       True
strtsmok     True
quitsmok     True
cholst      False
breast      False
mammog      False
papsm       False
prost       False
flusht      False
hearte      False
dtype: bool

In [150]:
numerical = list(df_full_train.dtypes[df_full_train.dtypes.ne("category")].index)[1:]
numerical

['agey', 'bmi', 'smokef', 'strtsmok', 'quitsmok']

In [177]:
ordinal = ["shlt"]

In [179]:
binary = [col for col in list(df_full_train.dtypes.index) if col not in numerical + ordinal][1:]
binary
df_full_train[binary].nunique()

ragender    2
hibpe       2
diabe       2
cancre      2
respe       2
hrtatte     2
stroke      2
arthre      2
vigact      2
smokev      2
smoken      2
cholst      2
breast      2
mammog      2
papsm       2
prost       2
flusht      2
hearte      2
dtype: int64

In [180]:
df_full_train[numerical]

       agey        bmi  smokef  strtsmok  quitsmok
0      85.0  22.222221     0.0       NaN       7.0
1      65.0  23.781212     0.0      14.0       1.0
2      69.0  30.477968     0.0      17.0      49.0
3      88.0        NaN     0.0      40.0      30.0
4      86.0        NaN     0.0      36.0       NaN
...     ...        ...     ...       ...       ...
61077  65.0  45.196281     0.0      20.0      15.0
61078  65.0        NaN     0.0       NaN       NaN
61079  51.0  25.153149     0.0       NaN       NaN
61080  77.0  33.792473     0.0       NaN       NaN
61081  63.0  22.491348     0.0      12.0      30.0

[61082 rows x 5 columns]

In [181]:
df_full_train[numerical].corrwith(df_full_train.hosp1y)

agey        0.088948
bmi        -0.005099
smokef     -0.022801
strtsmok    0.000730
quitsmok    0.036702
dtype: float64

In [182]:
for col in binary:
    print(col, "->", df_full_train[col].unique())

ragender -> ['2.Woman', '1.Man']
Categories (2, object): ['1.Man' < '2.Woman']
hibpe -> ['1.yes', '0.no', NaN]
Categories (2, object): ['0.no' < '1.yes']
diabe -> ['0.no', '1.yes', NaN]
Categories (2, object): ['0.no' < '1.yes']
cancre -> ['0.no', '1.yes', NaN]
Categories (2, object): ['0.no' < '1.yes']
respe -> ['0.no', '1.yes', NaN]
Categories (2, object): ['0.no' < '1.yes']
hrtatte -> ['0.no', '1.yes', NaN]
Categories (2, object): ['0.no' < '1.yes']
stroke -> ['0.no', '1.yes', NaN]
Categories (2, object): ['0.no' < '1.yes']
arthre -> ['1.yes', '0.no', NaN]
Categories (2, object): ['0.no' < '1.yes']
vigact -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']
smokev -> ['1.Yes', '0.No', NaN]
Categories (2, object): ['0.No' < '1.Yes']
smoken -> ['0.No', '1.Yes', NaN]
Categories (2, object): ['0.No' < '1.Yes']
cholst -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']
breast -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']
mammog -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']
papsm -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']
prost -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']
flusht -> [NaN, '1.Yes', '0.No']
Categories (2, object): ['0.No' < '1.Yes']
hearte -> [NaN, '0.no', '1.yes']
Categories (2, object): ['0.no' < '1.yes']

In [207]:
from sklearn.feature_extraction import DictVectorizer
from sklearn.impute import SimpleImputer

In [204]:
train_dicts = df_train[binary + numerical].to_dict(orient="records")

In [205]:
dv = DictVectorizer(sparse=False)

In [206]:
X_train = dv.fit_transform(train_dicts)

In [208]:
imputer = SimpleImputer(strategy='constant', fill_value=0)
X_train = imputer.fit_transform(X_train)

In [211]:
val_dicts = df_val[binary + numerical].to_dict(orient="records")

In [212]:
X_val = dv.transform(val_dicts)

In [213]:
X_val = imputer.fit(X_val)

## Logistic Regression

In [214]:
from sklearn.linear_model import LogisticRegression

In [218]:
model = LogisticRegression()
model.fit(X_train, y_train)

/home/giraldiego/.pyenv/versions/3.10.13/envs/ne1ai-final_project/lib/python3.10/site-packages/sklearn/linear_model/_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [219]:
model.predict_proba(X_val)

ValueError: Expected 2D array, got scalar array instead:
array=SimpleImputer(fill_value=0, strategy='constant').
Reshape your data either using array.reshape(-1, 1) if your data has a single feature or array.reshape(1, -1) if it contains a single sample.