In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
pd.set_option("display.max_columns", 200)

In [3]:
data_path = "dataset/H_MHAS_c2.dta" 
df = pd.read_stata(data_path)

In [4]:
df.shape

(26839, 5241)

In [5]:
df.head(5)

,codent01,codent03,ps3,ent2,np,unhhidnp,rahhidnp,tipent_01,tipent_03,tipent_12,tipent_15,tipent_18,unhhid,cunicah,h1hhid,h2hhid,h3hhid,h4hhid,h5hhid,h1hhidc,h2hhidc,h3hhidc,h4hhidc,h5hhidc,acthog,subhog_01,subhog_03,subhog_12,subhog_15,subhog_18,s1hhidnp,s2hhidnp,s3hhidnp,s4hhidnp,s5hhidnp,inw1,inw2,inw3,inw4,inw5,r1iwstat,r2iwstat,r3iwstat,r4iwstat,r5iwstat,s1iwstat,s2iwstat,s3iwstat,s4iwstat,s5iwstat,hacohort,r1proxy,r2proxy,r3proxy,r4proxy,r5proxy,s1proxy,s2proxy,s3proxy,s4proxy,s5proxy,h1hhresp,h2hhresp,h3hhresp,h4hhresp,h5hhresp,h1cpl,h2cpl,h3cpl,h4cpl,h5cpl,r1wthh,r2wthh,r3wthh,r4wthh,r5wthh,r1wtresp,r2wtresp,r3wtresp,r4wtresp,r5wtresp,s1wtresp,s2wtresp,s3wtresp,s4wtresp,s5wtresp,r1iwm,r2iwm,r3iwm,r4iwm,r5iwm,s1iwm,s2iwm,s3iwm,s4iwm,s5iwm,r1iwy,r2iwy,r3iwy,r4iwy,...,s2fsad,s3fsad,s4fsad,s5fsad,r1ftired,r2ftired,r3ftired,r4ftired,r5ftired,s1ftired,s2ftired,s3ftired,s4ftired,s5ftired,r1energ,r2energ,r3energ,r4energ,r5energ,s1energ,s2energ,s3energ,s4energ,s5energ,r1cesd_m,r2cesd_m,r3cesd_m,r4cesd_m,r5cesd_m,s1cesd_m,s2cesd_m,s3cesd_m,s4cesd_m,s5cesd_m,r1cesdm_m,r2cesdm_m,r3cesdm_m,r4cesdm_m,r5cesdm_m,s1cesdm_m,s2cesdm_m,s3cesdm_m,s4cesdm_m,s5cesdm_m,r3lideal3,r4lideal3,r5lideal3,s3lideal3,s4lideal3,s5lideal3,r3lexcl3,r4lexcl3,r5lexcl3,s3lexcl3,s4lexcl3,s5lexcl3,r3lstsf3,r4lstsf3,r5lstsf3,s3lstsf3,s4lstsf3,s5lstsf3,r3limptt3,r4limptt3,r5limptt3,s3limptt3,s4limptt3,s5limptt3,r3lchnot3,r4lchnot3,r5lchnot3,s3lchnot3,s4lchnot3,s5lchnot3,r3lsatsc3,r4lsatsc3,r5lsatsc3,s3lsatsc3,s4lsatsc3,s5lsatsc3,r3lsatsc3m,r4lsatsc3m,r5lsatsc3m,s3lsatsc3m,s4lsatsc3m,s5lsatsc3m,r3satlife_m,r4satlife_m,r5satlife_m,s3satlife_m,s4satlife_m,s5satlife_m,r3satlifez,r4satlifez,r5satlifez,s3satlifez,s4satlifez,s5satlifez,r2cantril,s2cantril
0,1.Selected person,1.Selected person in 2001,1.0,1.0,10,110.0,110,"12.Direct, second interview","12.Direct, second interview","1.Direct, follow-up interview",NaN,NaN,1,1,10.0,11.0,11.0,41.0,109.0,10,11,11,41,109,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010",31.NP=010 Deceased,99.Not part of the study,120.0,120.0,120.0,NaN,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","0.Non, resp","0.Non, resp","1.Resp, alive","1.Resp, alive","1.Resp, alive","5.NR, died this wave","6.NR, died prev wave","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,NaN,Baseline sample,0.Not proxy,0.Not proxy,0.Not proxy,NaN,NaN,0.Not proxy,0.Not proxy,0.Not proxy,NaN,NaN,2.0,2.0,2.0,NaN,NaN,1.Yes,1.Yes,1.Yes,NaN,NaN,312.0,314.0,313.0,444.0,NaN,300.0,314.0,329.0,296.0,NaN,300.0,314.0,329.0,NaN,NaN,7.0,8.0,11.0,NaN,NaN,7.0,8.0,11.0,NaN,NaN,2001.0,2003.0,2012.0,NaN,...,0.No,0.No,NaN,NaN,1.Yes,1.Yes,1.Yes,NaN,NaN,0.No,0.No,0.No,NaN,NaN,1.Yes,0.No,0.No,NaN,NaN,1.Yes,0.No,1.Yes,NaN,NaN,7.0,3.0,9.0,NaN,NaN,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,0.0,0.0,0.0,NaN,NaN,3.Agree,NaN,NaN,3.Agree,NaN,NaN,3.Agree,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,3.Agree,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,2.6,NaN,NaN,2.2,NaN,NaN,0,5,5,0.0,NaN,NaN,2.Neutral,NaN,NaN,2.Neutral,NaN,NaN,1.510731,NaN,NaN,1.510731,NaN,NaN,1.0,NaN
1,2.Spouse of selected person,2.Spouse of selected person in 2001,2.0,2.0,20,120.0,120,"11.Direct, first interview","11.Direct, first interview","1.Direct, follow-up interview","1.Direct, follow-up interview","1.Direct, follow-up interview",1,1,10.0,11.0,11.0,22.0,22.0,10,11,11,22,22,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010",12.New HH contains NP=020,12.New HH contains NP=020,110.0,110.0,110.0,NaN,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,NaN,Baseline sample,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,NaN,NaN,2.0,2.0,2.0,1.0,1.0,1.Yes,1.Yes,1.Yes,0.No,0.No,312.0,314.0,313.0,444.0,296.0,300.0,314.0,329.0,296.0,288.0,300.0,314.0,329.0,NaN,NaN,7.0,8.0,11.0,11.0,12.0,7.0,8.0,11.0,NaN,NaN,2001.0,2003.0,2012.0,2015.0,...,0.No,1.Yes,NaN,NaN,0.No,0.No,0.No,1.Yes,1.Yes,1.Yes,1.Yes,1.Yes,NaN,NaN,1.Yes,0.No,1.Yes,0.No,1.Yes,1.Yes,0.No,0.No,NaN,NaN,1.0,1.0,0.0,6.0,3.0,7.0,3.0,9.0,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,3.Agree,3.Agree,3.Agree,3.Agree,NaN,NaN,2.Neutral,2.Neutral,3.Agree,3.Agree,NaN,NaN,2.Neutral,3.Agree,3.Agree,2.Neutral,NaN,NaN,2.Neutral,3.Agree,3.Agree,3.Agree,NaN,NaN,2.Neutral,3.Agree,3.Agree,2.Neutral,NaN,NaN,2.2,2.8,3.0,2.6,NaN,NaN,0,0,0,0.0,NaN,NaN,2.Neutral,1.Agree,1.Agree,2.Neutral,NaN,NaN,1.510731,-0.387025,-0.393398,1.510731,NaN,NaN,NaN,1.0
2,1.Selected person,1.Selected person in 2001,1.0,1.0,10,210.0,210,"11.Direct, first interview","22.Proxy, second interview","1.Direct, follow-up interview","1.Direct, follow-up interview","1.Direct, follow-up interview",2,2,20.0,21.0,21.0,21.0,31.0,20,21,21,21,31,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010","01.No change, HH contains NP=010",11.New HH contains NP=010,220.0,220.0,220.0,220.0,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,Baseline sample,0.Not proxy,1.Proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,1.Proxy,1.Proxy,NaN,2.0,2.0,2.0,2.0,1.0,1.Yes,1.Yes,1.Yes,1.Yes,0.No,263.0,265.0,264.0,375.0,250.0,253.0,265.0,278.0,250.0,273.0,0.0,0.0,0.0,239.0,NaN,6.0,6.0,11.0,10.0,12.0,6.0,6.0,10.0,10.0,NaN,2001.0,2003.0,2012.0,2015.0,...,1.Yes,NaN,NaN,NaN,1.Yes,NaN,1.Yes,1.Yes,1.Yes,1.Yes,0.No,NaN,NaN,NaN,0.No,NaN,0.No,0.No,1.Yes,0.No,0.No,NaN,NaN,NaN,4.0,NaN,8.0,7.0,1.0,2.0,4.0,NaN,NaN,NaN,0.0,9.0,0.0,0.0,0.0,0.0,0.0,9.0,9.0,NaN,3.Agree,2.Neutral,3.Agree,NaN,NaN,NaN,3.Agree,2.Neutral,3.Agree,NaN,NaN,NaN,3.Agree,3.Agree,3.Agree,NaN,NaN,NaN,3.Agree,3.Agree,3.Agree,NaN,NaN,NaN,3.Agree,3.Agree,3.Agree,NaN,NaN,NaN,3.0,2.6,3.0,NaN,NaN,NaN,0,0,0,5.0,5.0,NaN,1.Agree,1.Agree,1.Agree,NaN,NaN,NaN,-0.397267,-0.387025,-0.393398,NaN,NaN,NaN,NaN,5.0
3,2.Spouse of selected person,2.Spouse of selected person in 2001,2.0,2.0,20,220.0,220,"12.Direct, second interview","11.Direct, first interview","3.Proxy, follow-up interview","3.Proxy, follow-up interview",NaN,2,2,20.0,21.0,21.0,21.0,52.0,20,21,21,21,52,00,00.Baseline HH,"01.No change, HH contains NP=010","01.No change, HH contains NP=010","01.No change, HH contains NP=010",32.NP=020 Deceased,210.0,210.0,210.0,210.0,NaN,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","0.Non, resp","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","5.NR, died this wave","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",NaN,Baseline sample,0.Not proxy,0.Not proxy,1.Proxy,1.Proxy,NaN,0.Not proxy,1.Proxy,0.Not proxy,0.Not proxy,NaN,2.0,2.0,2.0,2.0,NaN,1.Yes,1.Yes,1.Yes,1.Yes,NaN,263.0,0.0,264.0,375.0,250.0,0.0,0.0,0.0,239.0,239.0,253.0,265.0,278.0,250.0,NaN,6.0,6.0,10.0,10.0,NaN,6.0,6.0,11.0,10.0,NaN,2001.0,2003.0,2012.0,2015.0,...,NaN,1.Yes,1.Yes,NaN,1.Yes,0.No,NaN,NaN,NaN,1.Yes,NaN,1.Yes,1.Yes,NaN,0.No,0.No,NaN,NaN,NaN,0.No,NaN,0.No,0.No,NaN,2.0,4.0,NaN,NaN,NaN,4.0,NaN,8.0,7.0,NaN,0.0,0.0,9.0,9.0,NaN,0.0,9.0,0.0,0.0,NaN,NaN,NaN,NaN,3.Agree,2.Neutral,NaN,NaN,NaN,NaN,3.Agree,2.Neutral,NaN,NaN,NaN,NaN,3.Agree,3.Agree,NaN,NaN,NaN,NaN,3.Agree,3.Agree,NaN,NaN,NaN,NaN,3.Agree,3.Agree,NaN,NaN,NaN,NaN,3.0,2.6,NaN,5,5,5,0.0,0.0,NaN,NaN,NaN,NaN,1.Agree,1.Agree,NaN,NaN,NaN,NaN,-0.397267,-0.387025,NaN,5.0,NaN
4,1.Selected person,1.Selected person in 2001,1.0,1.0,10,310.0,310,"11.Direct, first interview","11.Direct, first interview","1.Direct, follow-up interview","1.Direct, follow-up interview","1.Direct, follow-up interview",3,3,30.0,41.0,31.0,31.0,31.0,30,41,31,31,31,01,00.Baseline HH,11.New HH contains NP=010,"01.No change, HH contains NP=010","01.No change, HH contains NP=010","01.No change, HH contains NP=010",311.0,311.0,311.0,311.0,311.0,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",0.Inap,"1.Resp, alive","1.Resp, alive","1.Resp, alive","1.Resp, alive",Baseline sample,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,NaN,0.Not proxy,0.Not proxy,0.Not proxy,0.Not proxy,1.0,2.0,2.0,2.0,2.0,0.No,1.Yes,1.Yes,1.Yes,1.Yes,471.0,475.0,472.0,669.0,448.0,454.0,475.0,498.0,448.0,435.0,NaN,471.0,494.0,0.0,448.0,6.0,8.0,11.0,11.0,12.0,NaN,8.0,10.0,11.0,12.0,2001.0,2003.0,2012.0,2015.0,...,0.No,0.No,0.No,1.Yes,0.No,0.No,0.No,0.No,1.Yes,NaN,0.No,1.Yes,0.No,1.Yes,0.No,1.Yes,0.No,0.No,0.No,NaN,0.No,1.Yes,1.Yes,1.Yes,3.0,0.0,2.0,1.0,3.0,NaN,1.0,3.0,1.0,5.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,2.Neutral,3.Agree,2.Neutral,3.Agree,3.Agree,1.Disagree,2.Neutral,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,3.Agree,2.Neutral,3.Agree,3.Agree,1.Disagree,3.Agree,3.Agree,2.4,3.0,2.8,2.6,3.0,2.6,0,0,0,0.0,0.0,0.0,1.Agree,1.Agree,1.Agree,1.Agree,1.Agree,1.Agree,-0.397267,-0.387025,-0.393398,-0.397267,-0.387025,-0.393398,1.0,NaN

In [6]:
column_names = list(df.columns.str.lower())
# column_names

In [7]:
df['unhhidnp'].describe()

count    2.683900e+04
mean     9.459864e+05
std      5.576727e+05
min      1.100000e+02
25%      4.707150e+05
50%      9.409100e+05
75%      1.385115e+06
max      2.021820e+06
Name: unhhidnp, dtype: float64

In [8]:
df['unhhidnp'].isna().sum()

0

In [9]:
# with open(r'column_names.txt', 'w') as fp:
#     fp.write('\n'.join(column_names))

In [71]:
target_columns = ['r1hosp1y',
 'r2hosp1y',
 'r3hosp1y',
 'r4hosp1y',
 'r5hosp1y']

In [89]:
picked_columns = [
"unhhidnp",
"rabyear",
"rabmonth",
"ragender",
"r1shlt",
"r2shlt",
"r3shlt",
"r4shlt",
"r5shlt",

"r1hibpe",
"r2hibpe",
"r3hibpe",
"r4hibpe",
"r5hibpe",
"r1diabe",
"r2diabe",
"r3diabe",
"r4diabe",
"r5diabe",
"r1cancre",
"r2cancre",
"r3cancre",
"r4cancre",
"r5cancre",
"r1respe",
"r2respe",
"r3respe",
"r4respe",
"r5respe",
"r1hrtatte",
"r2hrtatte",
"r3hrtatte",
"r4hrtatte",
"r5hrtatte",

"r4hearte",
"r5hearte",

"r1stroke",
"r2stroke",
"r3stroke",
"r4stroke",
"r5stroke",
"r1arthre",
"r2arthre",
"r3arthre",
"r4arthre",
"r5arthre",
"s5arthre",
]

In [90]:
screening = picked_columns + target_columns
screening

['unhhidnp',
 'rabyear',
 'rabmonth',
 'ragender',
 'r1shlt',
 'r2shlt',
 'r3shlt',
 'r4shlt',
 'r5shlt',
 'r1hibpe',
 'r2hibpe',
 'r3hibpe',
 'r4hibpe',
 'r5hibpe',
 'r1diabe',
 'r2diabe',
 'r3diabe',
 'r4diabe',
 'r5diabe',
 'r1cancre',
 'r2cancre',
 'r3cancre',
 'r4cancre',
 'r5cancre',
 'r1respe',
 'r2respe',
 'r3respe',
 'r4respe',
 'r5respe',
 'r1hrtatte',
 'r2hrtatte',
 'r3hrtatte',
 'r4hrtatte',
 'r5hrtatte',
 'r4hearte',
 'r5hearte',
 'r1stroke',
 'r2stroke',
 'r3stroke',
 'r4stroke',
 'r5stroke',
 'r1arthre',
 'r2arthre',
 'r3arthre',
 'r4arthre',
 'r5arthre',
 's5arthre',
 'r1hosp1y',
 'r2hosp1y',
 'r3hosp1y',
 'r4hosp1y',
 'r5hosp1y']

In [91]:
df_sub = df[screening]
df_sub

,unhhidnp,rabyear,rabmonth,ragender,r1shlt,r2shlt,r3shlt,r4shlt,r5shlt,r1hibpe,r2hibpe,r3hibpe,r4hibpe,r5hibpe,r1diabe,r2diabe,r3diabe,r4diabe,r5diabe,r1cancre,r2cancre,r3cancre,r4cancre,r5cancre,r1respe,r2respe,r3respe,r4respe,r5respe,r1hrtatte,r2hrtatte,r3hrtatte,r4hrtatte,r5hrtatte,r4hearte,r5hearte,r1stroke,r2stroke,r3stroke,r4stroke,r5stroke,r1arthre,r2arthre,r3arthre,r4arthre,r5arthre,s5arthre,r1hosp1y,r2hosp1y,r3hosp1y,r4hosp1y,r5hosp1y
0,110.0,1941.0,10.0,1.Man,5.Poor,2.Very good,5.Poor,NaN,NaN,1.yes,1.yes,1.yes,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,NaN,NaN,0.no,0.no,0.no,NaN,NaN,0.no,0.no,0.no,NaN,NaN,NaN,1.Yes,0.No,0.No,NaN,NaN
1,120.0,1950.0,2.0,2.Woman,4.Fair,4.Fair,3.Good,3.Good,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,NaN,0.No,0.No,0.No,0.No,0.No
2,210.0,1932.0,6.0,1.Man,5.Poor,NaN,4.Fair,4.Fair,3.Good,0.no,0.no,0.no,0.no,1.yes,0.no,0.no,0.no,0.no,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,1.yes,1.yes,NaN,0.No,0.No,0.No,0.No,1.Yes
3,220.0,1942.0,3.0,2.Woman,3.Good,4.Fair,NaN,NaN,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,NaN,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.no,0.no,NaN,NaN,0.No,0.No,0.No,1.Yes,NaN
4,310.0,1950.0,6.0,1.Man,3.Good,3.Good,4.Fair,3.Good,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,1.yes,1.yes,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.No,0.No,0.No,0.No,0.No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26834,2021610.0,1963.0,10.0,2.Woman,NaN,NaN,NaN,NaN,3.Good,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,1.yes,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,NaN,0.No
26835,2021620.0,1962.0,6.0,1.Man,NaN,NaN,NaN,NaN,4.Fair,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,1.yes,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,NaN,0.No
26836,2021710.0,1967.0,7.0,2.Woman,NaN,NaN,NaN,NaN,4.Fair,NaN,NaN,NaN,NaN,1.yes,NaN,NaN,NaN,NaN,1.yes,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,NaN,1.Yes
26837,2021810.0,1963.0,10.0,1.Man,NaN,NaN,NaN,NaN,3.Good,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,NaN,0.No
26838,2021820.0,1960.0,6.0,2.Woman,NaN,NaN,NaN,NaN,5.Poor,NaN,NaN,NaN,NaN,1.yes,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,0.no,NaN,NaN,NaN,NaN,0.no,NaN,NaN,NaN,NaN,1.yes,NaN,NaN,NaN,NaN,NaN,0.No

In [92]:
vars_orig = screening[4:]
vars_orig

['r1shlt',
 'r2shlt',
 'r3shlt',
 'r4shlt',
 'r5shlt',
 'r1hibpe',
 'r2hibpe',
 'r3hibpe',
 'r4hibpe',
 'r5hibpe',
 'r1diabe',
 'r2diabe',
 'r3diabe',
 'r4diabe',
 'r5diabe',
 'r1cancre',
 'r2cancre',
 'r3cancre',
 'r4cancre',
 'r5cancre',
 'r1respe',
 'r2respe',
 'r3respe',
 'r4respe',
 'r5respe',
 'r1hrtatte',
 'r2hrtatte',
 'r3hrtatte',
 'r4hrtatte',
 'r5hrtatte',
 'r4hearte',
 'r5hearte',
 'r1stroke',
 'r2stroke',
 'r3stroke',
 'r4stroke',
 'r5stroke',
 'r1arthre',
 'r2arthre',
 'r3arthre',
 'r4arthre',
 'r5arthre',
 's5arthre',
 'r1hosp1y',
 'r2hosp1y',
 'r3hosp1y',
 'r4hosp1y',
 'r5hosp1y']

In [93]:
from collections import OrderedDict
vars_clean = list(OrderedDict.fromkeys([name[2:] for name in vars_orig]))
vars_clean

['shlt',
 'hibpe',
 'diabe',
 'cancre',
 'respe',
 'hrtatte',
 'hearte',
 'stroke',
 'arthre',
 'hosp1y']

In [94]:
final_columns = ["unhhidnp", "wave"] + vars_clean
final_columns

['unhhidnp',
 'wave',
 'shlt',
 'hibpe',
 'diabe',
 'cancre',
 'respe',
 'hrtatte',
 'hearte',
 'stroke',
 'arthre',
 'hosp1y']

In [134]:
from pprint import pprint

# Initialize an empty DataFrame with the desired final columns
accumulated_df = pd.DataFrame(columns=final_columns)

# Loop over the wave numbers
for wave in range(1, 6):
    # Create new column names for the current wave
    _names = [f"r{wave}{var}" for var in vars_clean]
    wave_column_names = [name for name in _names if name in df_sub.columns] # Only keep valid column names
    # print(wave_column_names)
    column_mapping = {name: name[2:] for name in wave_column_names}  
    # print(column_mapping)

    # Select the necessary columns from the subset DataFrame and rename them
    wave_df = df_sub[["unhhidnp"] + wave_column_names]
    wave_df = wave_df.rename(columns=column_mapping)

    # Insert the wave number as a new column
    wave_df.insert(1, "wave", wave)

    # Append the current wave's DataFrame to the accumulated DataFrame
    accumulated_df = pd.concat([accumulated_df, wave_df])

/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])
/tmp/ipykernel_23200/2836855277.py:23: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  accumulated_df = pd.concat([accumulated_df, wave_df])

In [138]:
accumulated_df.shape

(134195, 12)

In [139]:
accumulated_df.dropna(subset=["hosp1y"])

,unhhidnp,wave,shlt,hibpe,diabe,cancre,respe,hrtatte,hearte,stroke,arthre,hosp1y
0,110.0,1,5.Poor,1.yes,0.no,0.no,0.no,0.no,NaN,0.no,0.no,1.Yes
1,120.0,1,4.Fair,0.no,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.No
2,210.0,1,5.Poor,0.no,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.No
3,220.0,1,3.Good,0.no,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.No
4,310.0,1,3.Good,0.no,0.no,0.no,0.no,0.no,NaN,0.no,0.no,0.No
...,...,...,...,...,...,...,...,...,...,...,...,...
26834,2021610.0,5,3.Good,0.no,0.no,0.no,0.no,0.no,1.yes,0.no,0.no,0.No
26835,2021620.0,5,4.Fair,0.no,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,0.No
26836,2021710.0,5,4.Fair,1.yes,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,1.Yes
26837,2021810.0,5,3.Good,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.no,0.No
26838,2021820.0,5,5.Poor,1.yes,0.no,0.no,0.no,0.no,0.no,0.no,1.yes,0.No